name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test_positive
        uses: actions/checkout@v2
        with:
          # Update Node.js version to 20
          node-version: '20'
