name: Run test_positive function

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test_positive function
        run: python main.py TestAddition.test_positive
