name: main.py
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: test_positive
      uses: actions/checkout@v2

    - name: test_negative
      run: python main.py run_function
