name: Run test_negative function

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: python main.py ${{inputs.TEST_FILTER}}
        run: python main.py ${{inputs.TEST_FILTER}}
