name: main.py

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: test_positive
        uses: actions/checkout@v2

      - name: test_positive
        run: python main.py
