name: python main.py ${{inputs.TEST_FILTER}}

on:
  workflow_dispatch:
    inputs:
      TEST_FILTER:
        description: target branch name
        default: 'TestAddition.test_negative'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: python main.py ${{inputs.TEST_FILTER}}
        run: python main.py ${{inputs.TEST_FILTER}}
